name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v4.9.1
        with:
          python-version: 3.12
      - uses: actions/cache@v4.2.3
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install uv
      - run: uv venv
      - run: source .venv/bin/activate
      - run: uv pip install -e .
      - run: pip install git+https://taddyb:${{ secrets.GHCR_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git
      - run: mkdocs build
      - run: mkdocs gh-deploy --force
